name: Add issues to the community board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - labeled

jobs:
  add-to-board:
    name: Add issue to the community board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # project 22 = oss community project
          project-url: https://github.com/orgs/anchore/projects/22
          github-token: ${{ secrets.OSS_PROJECT_GH_TOKEN }}
          labeled: bug, enhancement
          label-operator: OR
