name: "Validations"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  PYTHON_VERSION: "3.10"

jobs:
  Checks:
    name: "Checks"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/cache@v2
      with:
        path: venv
        key: ${{ hashFiles('requirements.txt') }}-${{ hashFiles('Makefile') }}

    - name: Run static-analysis
      run: make static-analysis

    - name: Run build-sboms
      run: make build-sboms
