name: "Validations"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  PYTHON_VERSION: "3.10"

jobs:
  Checks:
    name: "Checks"
    runs-on: ubuntu-20.04
    steps:
    - name: Maximize runner disk space
      run: |
        # Removes .NET runtime and libraries. (frees ~17 GB)
        sudo rm -rf /usr/share/dotnet
        # Removes Android SDKs and Tools. (frees ~11 GB)
        sudo rm -rf /usr/local/lib/android
        # Removes GHC (Haskell) artifacts. (frees ~2.7 GB)
        sudo rm -rf /opt/ghc

    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/cache@v2
      with:
        path: venv
        key: ${{ hashFiles('requirements.txt') }}-${{ hashFiles('Makefile') }}

    - name: Run static-analysis
      run: make static-analysis

    - name: Run build-sboms
      run: make build-sboms
